import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from '@/components/Sidebar'
import SessionProvider from '@/components/SessionProvider'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import Login from '@/components/Login/Login'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Chatgpt ',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions)
  
  return (
    <html lang="en">
         <body className={inter.className}>
<SessionProvider session={session}>
{!session ? (
<Login/>

):(
<div className='flex '>
  <div className="bg-black max-w-xs h-screen overflow-y-auto md:min-w-[20rem]">

<Sidebar />

  </div>


{/* main content  */}
<div className='bg-[#343541] flex-1'>
{children}
</div>


</div>

)
}
</SessionProvider>

</body>
    </html>
  )
}
